alias ll='ls -l'
alias e.='exit'
alias o.='open .'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias gcB='git checkout -B'
alias gc='git checkout'
alias gb='git branch'

alias swp='~/.dotfiles/wallpaper/setWallpaper.sh'