alias ll='ls -l'
alias c='${EDITOR:-vi}'
alias cat='bat'
alias cd='z'
alias o='open'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias Git='lazygit'
alias gcB='git checkout -B'
alias gc='git checkout'
alias gb='git branch'
alias airdrop='dropair'
alias cbclear='rm -rf /var/folders/sp/lmlqtk6x6n552ydfjn8kmzf00000gn/T/Clipboard/0/*'

alias updatebin='~/.dotfiles/bin/setup.sh'